# Generated by Django 5.2.4 on 2025-11-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='order',
        ),
    ]
