# Generated by Django 5.2.4 on 2025-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_remove_donation_message_remove_donation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
