# Generated by Django 5.2.4 on 2025-11-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_donation_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
