# Generated by Django 5.2.4 on 2025-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_donation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='raised_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
