# Generated by Django 5.2.4 on 2025-11-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
