# Generated by Django 5.2.4 on 2025-11-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_remove_gallery_description_remove_gallery_title'),
    ]

    operations = [
    ]
