# Generated by Django 5.2.4 on 2025-11-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_auto_20251114_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default='News', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
