# Generated by Django 5.2.4 on 2025-11-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0010_homecontent_learnmorecontent_learnmoreimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='work_video',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
