# Generated by Django 5.2.4 on 2025-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_remove_homecontent_hero_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('bg_color', models.CharField(default='bg-[#cae4f7]', max_length=50)),
                ('people_helped', models.IntegerField(default=0)),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('projects_completed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
