# Generated by Django 5.2.4 on 2025-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0012_donationcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_campaigns', models.IntegerField(default=0)),
                ('satisfied_donors', models.IntegerField(default=0)),
                ('fund_raised', models.IntegerField(default=0)),
                ('happy_volunteers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
